#+startup: overview nologdone
#+startup: showeverything
#+TITLE: Aquí (aqui.el) User Guide
#+SUBTITLE: for version {{{version}}}
#+AUTHOR: Charles Y. Choi
#+EMAIL: kickingvegas@gmail.com
#+OPTIONS: ':t toc:t author:t email:t H:4 f:t
#+LANGUAGE: en
#+MACRO: version 0.1.2-rc.1
#+MACRO: kbd (eval (org-texinfo-kbd-macro $1))
#+TEXINFO_FILENAME: aqui.info
#+TEXINFO_CLASS: casual
#+TEXINFO_HEADER: @syncodeindex pg cp
#+TEXINFO_HEADER: @paragraphindent none
#+TEXINFO_TITLEPAGE: t
#+TEXINFO_DIR_CATEGORY: Emacs misc features
#+TEXINFO_DIR_NAME: Aquí
#+TEXINFO_DIR_DESC: Location update optimized for macOS.
#+TEXINFO_PRINTED_TITLE: Aquí (aqui.el) User Guide

Version: {{{version}}}

#+TEXINFO: Copyright © 2026 @w{Charles Y. Choi}


Aquí (~aqui.el~) is an Elisp library for updating the location for GNU Emacs with optimization for high accuracy on macOS. On macOS, Aquí will use the Shortcuts app to obtain a location update from the native OS location service. This approach avoids needing a specialized third party executable to accomplish the location lookup. If Shortcuts is not available, Aquí will use a third party internet service to obtain location information.

Aquí updates the following Emacs variables:

- ~calendar-latitude~
- ~calendar-longitude~
- ~calendar-location-name~

These values are primarily used by the built-in library ~solar.el~, which provides the ~sunrise-sunset~ command ([[info:emacs#Sunrise/Sunset]]). Other third party commands providing local weather (e.g. [[https://github.com/kickingvegas/restlib/blob/main/examples/wttr.el][wttr]]) can take advantage of location updates.


#+INCLUDE: "./sponsorship.org"

* Copying
:PROPERTIES:
:COPYING: t
:END:

Copyright © 2026 Charles Y. Choi

* Features
:PROPERTIES:
:CUSTOM_ID: features
:END:
#+CINDEX: Features

- High-accuracy location update via macOS Location Service.

- Updates the following variables given a location update:

  - ~calendar-latitude~

  - ~calendar-longitude~

  - ~calendar-location-name~


* Requirements
:PROPERTIES:
:CUSTOM_ID: requirements
:END:
#+CINDEX: Requirements

- GNU Emacs 30.1+
- [[https://github.com/kickingvegas/restlib][restlib]] 0.1+
- macOS 15+ (Sequoia) if Shortcuts app is used


* Install
:PROPERTIES:
:CUSTOM_ID: install
:END:
#+CINDEX: Install
#+VINDEX: aqui
#+VINDEX: aqui-source
#+VINDEX: aqui-map-provider
#+VINDEX: aqui-glyph
#+VINDEX: aqui-inactive-glyph

Aquí is planned to be available on MELPA for installation via ~package-install~ (TBD).

There should be no setup required as commands provided by ~aqui.el~ are auto-loaded via ~package-install~.

#+TEXINFO: @subsubheading macOS Shortcuts Support

Install the following iCloud Shortcut to obtain high-accuracy location data:

- [[https://www.icloud.com/shortcuts/5199bce93e314120b4bb78f17406592e][iCloud Shortcut: Current Location JSON]]

Ensure that Aquí uses this Shortcut by setting the value of the customizable variable ~aqui-source~ to "Shortcuts" (~:shortcuts~)


#+TEXINFO: @subsubheading Customization

Customize Aquí via the ~customize-group~ command:

#+begin_example
  M-x customize-group aqui RET
#+end_example

From here you can customize the following variables:

- ~aqui-source~ ::

  Select where location data should be sourced from.

  The following sources are supported:

  - Shortcuts (~:shortcuts~)
  - ip-api.com  (~:ip-api~)


- ~aqui-map-provider~ ::

  Select which map provider to use (Apple, Google).

- ~aqui-glyph~ ::

  Aquí glyph to use when messaging location update.

  For SF Symbols support, run the command ~aqui-setup-sf-symbols~ to initialize support for rendering SF Symbols.

- ~aqui-inactive-glyph~ ::

  Aquí glyph to use for unexpected result in requesting a location update.

  For SF Symbols support, run the command ~aqui-setup-sf-symbols~ to initialize support for rendering SF Symbols.


* Usage
#+CINDEX: Usage
#+VINDEX: aqui
#+VINDEX: aqui-insert-location
#+VINDEX: aqui-customize-save-location-data
#+VINDEX: aqui-setup-sf-symbols

The following commands are provided by Aquí:

- Command: aqui ::

  Update current geographic location from ~aqui-source~.

  Given an location update, the following variables are run-time updated:

  - ~calendar-latitude~
  - ~calendar-longitude~
  - ~calendar-location-name~

  Use the command ~aqui-customize-save-location-data~ to persist these variables to a file.

- Command: aqui-insert-location &optional LOCATION ::

  - LOCATION: Location object

  Insert last obtained LOCATION as an Org table.

  This command requires that the command ~aqui~ be run beforehand.

- Command: aqui-customize-save-location-data ::

  Persist location data in calendar location variables.

  The following variables are persisted given a location update.

  - ~calendar-latitude~
  - ~calendar-longitude~
  - ~calendar-location-name~

- Command: aqui-setup-sf-symbols ::

  Setup usage of SF Symbols for glyphs.

  On macOS, the variables ~aqui-glyph~ and ~aqui-inactive-glyph~ can be configured to use SF Symbols. Run this command to correctly display these symbols in a GUI frame.

* Feedback & Discussion
#+CINDEX: Feedback
Please report any feedback about *Aquí* to the [[https://github.com/kickingvegas/aqui/issues][issue tracker on GitHub]].

#+CINDEX: Discussion
To participate in general discussion about using *Aquí*, please join the [[https://github.com/kickingvegas/aqui/discussions][discussion group]].

* Sponsorship
#+CINDEX: Sponsorship

#+INCLUDE: "./sponsorship.org"


* About
#+CINDEX: About

[[https://github.com/kickingvegas/aqui][Aquí]] was conceived and crafted by Charles Y. Choi in San Francisco, California.

Thank you for using *Aquí*.

Always choose love.

* Acknowledgments
#+CINDEX: Acknowledgments

Thanks to all the contributors to Core Location and  Shortcuts on macOS, and to the GNU Emacs ecosystem from which Aquí builds from. This work would not be possible without your efforts.


* Main Index
:PROPERTIES:
:INDEX:    cp
:END:

Index for this user guide.

* Variable Index
:PROPERTIES:
:INDEX:    vr
:END:

Variables, functions, commands, and menus referenced by this user guide.
